import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'es' | 'en' | 'pt' | 'fr' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

const translations: Record<Language, Record<string, string>> = {
  es: {
    'app.title': 'SecureVault',
    'app.tagline': 'Gestor de contraseñas seguro',

    'auth.signIn': 'Iniciar Sesión',
    'auth.signUp': 'Crear Cuenta',
    'auth.signOut': 'Salir',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.masterPassword': 'Contraseña Maestra',
    'auth.confirmMasterPassword': 'Confirmar Contraseña Maestra',
    'auth.welcomeBack': 'Bienvenido de nuevo',
    'auth.signInTagline': 'Inicia sesión para acceder a tu bóveda',
    'auth.createAccount': 'Crear Cuenta',
    'auth.createAccountTagline': 'Comienza a asegurar tus contraseñas hoy',
    'auth.accountPassword': 'Contraseña de Cuenta',
    'auth.accountPasswordHelp': 'Para iniciar sesión en tu cuenta',
    'auth.masterPasswordHelp': 'Requerida para descifrar tu bóveda',
    'auth.masterPasswordEncryptHelp': 'Usada para cifrar tu bóveda',
    'auth.dontHaveAccount': '¿No tienes una cuenta?',
    'auth.alreadyHaveAccount': '¿Ya tienes una cuenta?',
    'auth.signInLink': 'Iniciar sesión',
    'auth.signUpLink': 'Registrarse',

    'nav.home': 'Inicio',
    'nav.notifications': 'Centro de notificación',
    'nav.generator': 'Generador',
    'nav.share': 'Centro para compartir',
    'nav.analysis': 'Análisis de contraseñas',
    'nav.settings': 'Opciones',
    'nav.registeredUser': 'Usuario registrado',

    'vault.searchPlaceholder': 'Buscar en tu bóveda...',
    'vault.favorites': 'Favoritos',
    'vault.allItems': 'Todos los Elementos',
    'vault.passwords': 'Ingresos',
    'vault.wifi': 'Wi-Fi',
    'vault.addNew': 'Agregar Nuevo',
    'vault.addPassword': 'Agregar Contraseña',
    'vault.addWifi': 'Agregar Wi-Fi',
    'vault.edit': 'Editar',
    'vault.delete': 'Eliminar',
    'vault.copy': 'Copiar',
    'vault.copied': 'Copiado',
    'vault.showPassword': 'Mostrar contraseña',
    'vault.hidePassword': 'Ocultar contraseña',
    'vault.website': 'Sitio Web',
    'vault.username': 'Usuario',
    'vault.notes': 'Notas',
    'vault.category': 'Categoría',
    'vault.save': 'Guardar',
    'vault.cancel': 'Cancelar',
    'vault.deleteConfirm': '¿Estás seguro de que quieres eliminar este elemento?',

    'generator.title': 'Generador de Contraseñas',
    'generator.placeholder': 'Genera una contraseña segura',
    'generator.generate': 'Generar Contraseña',
    'generator.refresh': 'Generar nueva contraseña',
    'generator.copy': 'Copiar contraseña',
    'generator.strength': 'Fortaleza',
    'generator.weak': 'Débil',
    'generator.medium': 'Media',
    'generator.strong': 'Fuerte',
    'generator.options': 'Opciones',
    'generator.length': 'Longitud',
    'generator.uppercase': 'Mayúsculas (A-Z)',
    'generator.lowercase': 'Minúsculas (a-z)',
    'generator.numbers': 'Números (0-9)',
    'generator.symbols': 'Símbolos (!@#$%)',

    'notifications.title': 'Centro de Notificaciones',
    'notifications.unresolved': 'alertas sin resolver',
    'notifications.noNotifications': 'No tienes notificaciones',
    'notifications.unresolvedSection': 'Sin resolver',
    'notifications.resolvedSection': 'Resueltas',
    'notifications.markResolved': 'Marcar como resuelto',
    'notifications.delete': 'Eliminar',
    'notifications.resolvedOn': 'Resuelta el',

    'settings.title': 'Opciones',
    'settings.userInfo': 'Información del Usuario',
    'settings.registeredUser': 'Usuario registrado en SecureVault',
    'settings.export': 'Exportar Datos',
    'settings.exportJSON': 'Exportar como JSON',
    'settings.exportCSV': 'Exportar como CSV',
    'settings.exportHelp': 'Descarga una copia de seguridad de todas tus contraseñas',
    'settings.import': 'Importar Datos',
    'settings.selectFile': 'Seleccionar archivo JSON',
    'settings.importing': 'Importando...',
    'settings.importHelp': 'Importa contraseñas desde un archivo de respaldo',
    'settings.theme': 'Tema de Color',
    'settings.themeNote': 'Nota: Los cambios de tema se aplicarán en una futura actualización',
    'settings.about': 'Acerca de',
    'settings.version': 'Versión',
    'settings.contact': 'Contacto',
    'settings.aboutText': 'SecureVault - Gestor de contraseñas seguro con cifrado de extremo a extremo',
    'settings.language': 'Idioma',
    'settings.selectLanguage': 'Selecciona tu idioma preferido',

    'share.title': 'Centro para Compartir',
    'share.description': 'Comparte contraseñas de forma segura con otros usuarios',
    'share.comingSoon': 'Esta función estará disponible próximamente',

    'analysis.title': 'Análisis de Contraseñas',
    'analysis.description': 'Analiza la seguridad de tus contraseñas',
    'analysis.comingSoon': 'Esta función estará disponible próximamente',

    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
  },
  en: {
    'app.title': 'SecureVault',
    'app.tagline': 'Secure password manager',

    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.signOut': 'Sign Out',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.masterPassword': 'Master Password',
    'auth.confirmMasterPassword': 'Confirm Master Password',
    'auth.welcomeBack': 'Welcome Back',
    'auth.signInTagline': 'Sign in to access your vault',
    'auth.createAccount': 'Create Account',
    'auth.createAccountTagline': 'Start securing your passwords today',
    'auth.accountPassword': 'Account Password',
    'auth.accountPasswordHelp': 'For logging into your account',
    'auth.masterPasswordHelp': 'Required to decrypt your vault',
    'auth.masterPasswordEncryptHelp': 'Used to encrypt your vault',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.signInLink': 'Sign in',
    'auth.signUpLink': 'Sign up',

    'nav.home': 'Home',
    'nav.notifications': 'Notification Center',
    'nav.generator': 'Generator',
    'nav.share': 'Share Center',
    'nav.analysis': 'Password Analysis',
    'nav.settings': 'Settings',
    'nav.registeredUser': 'Registered user',

    'vault.searchPlaceholder': 'Search your vault...',
    'vault.favorites': 'Favorites',
    'vault.allItems': 'All Items',
    'vault.passwords': 'Logins',
    'vault.wifi': 'Wi-Fi',
    'vault.addNew': 'Add New',
    'vault.addPassword': 'Add Password',
    'vault.addWifi': 'Add Wi-Fi',
    'vault.edit': 'Edit',
    'vault.delete': 'Delete',
    'vault.copy': 'Copy',
    'vault.copied': 'Copied',
    'vault.showPassword': 'Show password',
    'vault.hidePassword': 'Hide password',
    'vault.website': 'Website',
    'vault.username': 'Username',
    'vault.notes': 'Notes',
    'vault.category': 'Category',
    'vault.save': 'Save',
    'vault.cancel': 'Cancel',
    'vault.deleteConfirm': 'Are you sure you want to delete this item?',

    'generator.title': 'Password Generator',
    'generator.placeholder': 'Generate a secure password',
    'generator.generate': 'Generate Password',
    'generator.refresh': 'Generate new password',
    'generator.copy': 'Copy password',
    'generator.strength': 'Strength',
    'generator.weak': 'Weak',
    'generator.medium': 'Medium',
    'generator.strong': 'Strong',
    'generator.options': 'Options',
    'generator.length': 'Length',
    'generator.uppercase': 'Uppercase (A-Z)',
    'generator.lowercase': 'Lowercase (a-z)',
    'generator.numbers': 'Numbers (0-9)',
    'generator.symbols': 'Symbols (!@#$%)',

    'notifications.title': 'Notification Center',
    'notifications.unresolved': 'unresolved alerts',
    'notifications.noNotifications': 'You have no notifications',
    'notifications.unresolvedSection': 'Unresolved',
    'notifications.resolvedSection': 'Resolved',
    'notifications.markResolved': 'Mark as resolved',
    'notifications.delete': 'Delete',
    'notifications.resolvedOn': 'Resolved on',

    'settings.title': 'Settings',
    'settings.userInfo': 'User Information',
    'settings.registeredUser': 'Registered user on SecureVault',
    'settings.export': 'Export Data',
    'settings.exportJSON': 'Export as JSON',
    'settings.exportCSV': 'Export as CSV',
    'settings.exportHelp': 'Download a backup copy of all your passwords',
    'settings.import': 'Import Data',
    'settings.selectFile': 'Select JSON file',
    'settings.importing': 'Importing...',
    'settings.importHelp': 'Import passwords from a backup file',
    'settings.theme': 'Color Theme',
    'settings.themeNote': 'Note: Theme changes will be applied in a future update',
    'settings.about': 'About',
    'settings.version': 'Version',
    'settings.contact': 'Contact',
    'settings.aboutText': 'SecureVault - Secure password manager with end-to-end encryption',
    'settings.language': 'Language',
    'settings.selectLanguage': 'Select your preferred language',

    'share.title': 'Share Center',
    'share.description': 'Share passwords securely with other users',
    'share.comingSoon': 'This feature will be available soon',

    'analysis.title': 'Password Analysis',
    'analysis.description': 'Analyze the security of your passwords',
    'analysis.comingSoon': 'This feature will be available soon',

    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
  },
  pt: {
    'app.title': 'SecureVault',
    'app.tagline': 'Gerenciador de senhas seguro',

    'auth.signIn': 'Entrar',
    'auth.signUp': 'Criar Conta',
    'auth.signOut': 'Sair',
    'auth.email': 'E-mail',
    'auth.password': 'Senha',
    'auth.masterPassword': 'Senha Mestra',
    'auth.confirmMasterPassword': 'Confirmar Senha Mestra',
    'auth.welcomeBack': 'Bem-vindo de volta',
    'auth.signInTagline': 'Entre para acessar seu cofre',
    'auth.createAccount': 'Criar Conta',
    'auth.createAccountTagline': 'Comece a proteger suas senhas hoje',
    'auth.accountPassword': 'Senha da Conta',
    'auth.accountPasswordHelp': 'Para fazer login na sua conta',
    'auth.masterPasswordHelp': 'Necessária para descriptografar seu cofre',
    'auth.masterPasswordEncryptHelp': 'Usada para criptografar seu cofre',
    'auth.dontHaveAccount': 'Não tem uma conta?',
    'auth.alreadyHaveAccount': 'Já tem uma conta?',
    'auth.signInLink': 'Entrar',
    'auth.signUpLink': 'Registrar-se',

    'nav.home': 'Início',
    'nav.notifications': 'Central de Notificações',
    'nav.generator': 'Gerador',
    'nav.share': 'Central de Compartilhamento',
    'nav.analysis': 'Análise de Senhas',
    'nav.settings': 'Configurações',
    'nav.registeredUser': 'Usuário registrado',

    'vault.searchPlaceholder': 'Pesquisar no seu cofre...',
    'vault.favorites': 'Favoritos',
    'vault.allItems': 'Todos os Itens',
    'vault.passwords': 'Logins',
    'vault.wifi': 'Wi-Fi',
    'vault.addNew': 'Adicionar Novo',
    'vault.addPassword': 'Adicionar Senha',
    'vault.addWifi': 'Adicionar Wi-Fi',
    'vault.edit': 'Editar',
    'vault.delete': 'Excluir',
    'vault.copy': 'Copiar',
    'vault.copied': 'Copiado',
    'vault.showPassword': 'Mostrar senha',
    'vault.hidePassword': 'Ocultar senha',
    'vault.website': 'Site',
    'vault.username': 'Usuário',
    'vault.notes': 'Notas',
    'vault.category': 'Categoria',
    'vault.save': 'Salvar',
    'vault.cancel': 'Cancelar',
    'vault.deleteConfirm': 'Tem certeza de que deseja excluir este item?',

    'generator.title': 'Gerador de Senhas',
    'generator.placeholder': 'Gere uma senha segura',
    'generator.generate': 'Gerar Senha',
    'generator.refresh': 'Gerar nova senha',
    'generator.copy': 'Copiar senha',
    'generator.strength': 'Força',
    'generator.weak': 'Fraca',
    'generator.medium': 'Média',
    'generator.strong': 'Forte',
    'generator.options': 'Opções',
    'generator.length': 'Comprimento',
    'generator.uppercase': 'Maiúsculas (A-Z)',
    'generator.lowercase': 'Minúsculas (a-z)',
    'generator.numbers': 'Números (0-9)',
    'generator.symbols': 'Símbolos (!@#$%)',

    'notifications.title': 'Central de Notificações',
    'notifications.unresolved': 'alertas não resolvidos',
    'notifications.noNotifications': 'Você não tem notificações',
    'notifications.unresolvedSection': 'Não resolvidos',
    'notifications.resolvedSection': 'Resolvidos',
    'notifications.markResolved': 'Marcar como resolvido',
    'notifications.delete': 'Excluir',
    'notifications.resolvedOn': 'Resolvido em',

    'settings.title': 'Configurações',
    'settings.userInfo': 'Informações do Usuário',
    'settings.registeredUser': 'Usuário registrado no SecureVault',
    'settings.export': 'Exportar Dados',
    'settings.exportJSON': 'Exportar como JSON',
    'settings.exportCSV': 'Exportar como CSV',
    'settings.exportHelp': 'Baixe uma cópia de backup de todas as suas senhas',
    'settings.import': 'Importar Dados',
    'settings.selectFile': 'Selecionar arquivo JSON',
    'settings.importing': 'Importando...',
    'settings.importHelp': 'Importe senhas de um arquivo de backup',
    'settings.theme': 'Tema de Cores',
    'settings.themeNote': 'Nota: As alterações de tema serão aplicadas em uma atualização futura',
    'settings.about': 'Sobre',
    'settings.version': 'Versão',
    'settings.contact': 'Contato',
    'settings.aboutText': 'SecureVault - Gerenciador de senhas seguro com criptografia de ponta a ponta',
    'settings.language': 'Idioma',
    'settings.selectLanguage': 'Selecione seu idioma preferido',

    'share.title': 'Central de Compartilhamento',
    'share.description': 'Compartilhe senhas com segurança com outros usuários',
    'share.comingSoon': 'Este recurso estará disponível em breve',

    'analysis.title': 'Análise de Senhas',
    'analysis.description': 'Analise a segurança de suas senhas',
    'analysis.comingSoon': 'Este recurso estará disponível em breve',

    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
  },
  fr: {
    'app.title': 'SecureVault',
    'app.tagline': 'Gestionnaire de mots de passe sécurisé',

    'auth.signIn': 'Se Connecter',
    'auth.signUp': 'Créer un Compte',
    'auth.signOut': 'Se Déconnecter',
    'auth.email': 'E-mail',
    'auth.password': 'Mot de passe',
    'auth.masterPassword': 'Mot de passe principal',
    'auth.confirmMasterPassword': 'Confirmer le mot de passe principal',
    'auth.welcomeBack': 'Bienvenue',
    'auth.signInTagline': 'Connectez-vous pour accéder à votre coffre',
    'auth.createAccount': 'Créer un compte',
    'auth.createAccountTagline': 'Commencez à sécuriser vos mots de passe aujourd\'hui',
    'auth.accountPassword': 'Mot de passe du compte',
    'auth.accountPasswordHelp': 'Pour vous connecter à votre compte',
    'auth.masterPasswordHelp': 'Requis pour déchiffrer votre coffre',
    'auth.masterPasswordEncryptHelp': 'Utilisé pour chiffrer votre coffre',
    'auth.dontHaveAccount': 'Vous n\'avez pas de compte?',
    'auth.alreadyHaveAccount': 'Vous avez déjà un compte?',
    'auth.signInLink': 'Se connecter',
    'auth.signUpLink': 'S\'inscrire',

    'nav.home': 'Accueil',
    'nav.notifications': 'Centre de notifications',
    'nav.generator': 'Générateur',
    'nav.share': 'Centre de partage',
    'nav.analysis': 'Analyse des mots de passe',
    'nav.settings': 'Paramètres',
    'nav.registeredUser': 'Utilisateur enregistré',

    'vault.searchPlaceholder': 'Rechercher dans votre coffre...',
    'vault.favorites': 'Favoris',
    'vault.allItems': 'Tous les éléments',
    'vault.passwords': 'Connexions',
    'vault.wifi': 'Wi-Fi',
    'vault.addNew': 'Ajouter nouveau',
    'vault.addPassword': 'Ajouter un mot de passe',
    'vault.addWifi': 'Ajouter Wi-Fi',
    'vault.edit': 'Modifier',
    'vault.delete': 'Supprimer',
    'vault.copy': 'Copier',
    'vault.copied': 'Copié',
    'vault.showPassword': 'Afficher le mot de passe',
    'vault.hidePassword': 'Masquer le mot de passe',
    'vault.website': 'Site web',
    'vault.username': 'Nom d\'utilisateur',
    'vault.notes': 'Notes',
    'vault.category': 'Catégorie',
    'vault.save': 'Enregistrer',
    'vault.cancel': 'Annuler',
    'vault.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer cet élément?',

    'generator.title': 'Générateur de mots de passe',
    'generator.placeholder': 'Générer un mot de passe sécurisé',
    'generator.generate': 'Générer un mot de passe',
    'generator.refresh': 'Générer un nouveau mot de passe',
    'generator.copy': 'Copier le mot de passe',
    'generator.strength': 'Force',
    'generator.weak': 'Faible',
    'generator.medium': 'Moyen',
    'generator.strong': 'Fort',
    'generator.options': 'Options',
    'generator.length': 'Longueur',
    'generator.uppercase': 'Majuscules (A-Z)',
    'generator.lowercase': 'Minuscules (a-z)',
    'generator.numbers': 'Chiffres (0-9)',
    'generator.symbols': 'Symboles (!@#$%)',

    'notifications.title': 'Centre de notifications',
    'notifications.unresolved': 'alertes non résolues',
    'notifications.noNotifications': 'Vous n\'avez aucune notification',
    'notifications.unresolvedSection': 'Non résolues',
    'notifications.resolvedSection': 'Résolues',
    'notifications.markResolved': 'Marquer comme résolu',
    'notifications.delete': 'Supprimer',
    'notifications.resolvedOn': 'Résolu le',

    'settings.title': 'Paramètres',
    'settings.userInfo': 'Informations utilisateur',
    'settings.registeredUser': 'Utilisateur enregistré sur SecureVault',
    'settings.export': 'Exporter les données',
    'settings.exportJSON': 'Exporter en JSON',
    'settings.exportCSV': 'Exporter en CSV',
    'settings.exportHelp': 'Téléchargez une copie de sauvegarde de tous vos mots de passe',
    'settings.import': 'Importer des données',
    'settings.selectFile': 'Sélectionner un fichier JSON',
    'settings.importing': 'Importation...',
    'settings.importHelp': 'Importez des mots de passe depuis un fichier de sauvegarde',
    'settings.theme': 'Thème de couleur',
    'settings.themeNote': 'Note: Les changements de thème seront appliqués dans une mise à jour future',
    'settings.about': 'À propos',
    'settings.version': 'Version',
    'settings.contact': 'Contact',
    'settings.aboutText': 'SecureVault - Gestionnaire de mots de passe sécurisé avec chiffrement de bout en bout',
    'settings.language': 'Langue',
    'settings.selectLanguage': 'Sélectionnez votre langue préférée',

    'share.title': 'Centre de partage',
    'share.description': 'Partagez des mots de passe en toute sécurité avec d\'autres utilisateurs',
    'share.comingSoon': 'Cette fonctionnalité sera bientôt disponible',

    'analysis.title': 'Analyse des mots de passe',
    'analysis.description': 'Analysez la sécurité de vos mots de passe',
    'analysis.comingSoon': 'Cette fonctionnalité sera bientôt disponible',

    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
  },
  de: {
    'app.title': 'SecureVault',
    'app.tagline': 'Sicherer Passwort-Manager',

    'auth.signIn': 'Anmelden',
    'auth.signUp': 'Konto Erstellen',
    'auth.signOut': 'Abmelden',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.masterPassword': 'Master-Passwort',
    'auth.confirmMasterPassword': 'Master-Passwort bestätigen',
    'auth.welcomeBack': 'Willkommen zurück',
    'auth.signInTagline': 'Melden Sie sich an, um auf Ihren Tresor zuzugreifen',
    'auth.createAccount': 'Konto erstellen',
    'auth.createAccountTagline': 'Beginnen Sie noch heute, Ihre Passwörter zu sichern',
    'auth.accountPassword': 'Kontopasswort',
    'auth.accountPasswordHelp': 'Für die Anmeldung bei Ihrem Konto',
    'auth.masterPasswordHelp': 'Erforderlich zum Entschlüsseln Ihres Tresors',
    'auth.masterPasswordEncryptHelp': 'Wird zum Verschlüsseln Ihres Tresors verwendet',
    'auth.dontHaveAccount': 'Haben Sie kein Konto?',
    'auth.alreadyHaveAccount': 'Haben Sie bereits ein Konto?',
    'auth.signInLink': 'Anmelden',
    'auth.signUpLink': 'Registrieren',

    'nav.home': 'Startseite',
    'nav.notifications': 'Benachrichtigungszentrale',
    'nav.generator': 'Generator',
    'nav.share': 'Freigabezentrale',
    'nav.analysis': 'Passwortanalyse',
    'nav.settings': 'Einstellungen',
    'nav.registeredUser': 'Registrierter Benutzer',

    'vault.searchPlaceholder': 'Durchsuchen Sie Ihren Tresor...',
    'vault.favorites': 'Favoriten',
    'vault.allItems': 'Alle Elemente',
    'vault.passwords': 'Anmeldungen',
    'vault.wifi': 'Wi-Fi',
    'vault.addNew': 'Neu hinzufügen',
    'vault.addPassword': 'Passwort hinzufügen',
    'vault.addWifi': 'Wi-Fi hinzufügen',
    'vault.edit': 'Bearbeiten',
    'vault.delete': 'Löschen',
    'vault.copy': 'Kopieren',
    'vault.copied': 'Kopiert',
    'vault.showPassword': 'Passwort anzeigen',
    'vault.hidePassword': 'Passwort ausblenden',
    'vault.website': 'Webseite',
    'vault.username': 'Benutzername',
    'vault.notes': 'Notizen',
    'vault.category': 'Kategorie',
    'vault.save': 'Speichern',
    'vault.cancel': 'Abbrechen',
    'vault.deleteConfirm': 'Möchten Sie dieses Element wirklich löschen?',

    'generator.title': 'Passwort-Generator',
    'generator.placeholder': 'Generieren Sie ein sicheres Passwort',
    'generator.generate': 'Passwort generieren',
    'generator.refresh': 'Neues Passwort generieren',
    'generator.copy': 'Passwort kopieren',
    'generator.strength': 'Stärke',
    'generator.weak': 'Schwach',
    'generator.medium': 'Mittel',
    'generator.strong': 'Stark',
    'generator.options': 'Optionen',
    'generator.length': 'Länge',
    'generator.uppercase': 'Großbuchstaben (A-Z)',
    'generator.lowercase': 'Kleinbuchstaben (a-z)',
    'generator.numbers': 'Zahlen (0-9)',
    'generator.symbols': 'Symbole (!@#$%)',

    'notifications.title': 'Benachrichtigungszentrale',
    'notifications.unresolved': 'ungelöste Warnungen',
    'notifications.noNotifications': 'Sie haben keine Benachrichtigungen',
    'notifications.unresolvedSection': 'Ungelöst',
    'notifications.resolvedSection': 'Gelöst',
    'notifications.markResolved': 'Als gelöst markieren',
    'notifications.delete': 'Löschen',
    'notifications.resolvedOn': 'Gelöst am',

    'settings.title': 'Einstellungen',
    'settings.userInfo': 'Benutzerinformationen',
    'settings.registeredUser': 'Registrierter Benutzer auf SecureVault',
    'settings.export': 'Daten exportieren',
    'settings.exportJSON': 'Als JSON exportieren',
    'settings.exportCSV': 'Als CSV exportieren',
    'settings.exportHelp': 'Laden Sie eine Sicherungskopie aller Ihrer Passwörter herunter',
    'settings.import': 'Daten importieren',
    'settings.selectFile': 'JSON-Datei auswählen',
    'settings.importing': 'Importieren...',
    'settings.importHelp': 'Importieren Sie Passwörter aus einer Sicherungsdatei',
    'settings.theme': 'Farbthema',
    'settings.themeNote': 'Hinweis: Themenänderungen werden in einem zukünftigen Update angewendet',
    'settings.about': 'Über',
    'settings.version': 'Version',
    'settings.contact': 'Kontakt',
    'settings.aboutText': 'SecureVault - Sicherer Passwort-Manager mit Ende-zu-Ende-Verschlüsselung',
    'settings.language': 'Sprache',
    'settings.selectLanguage': 'Wählen Sie Ihre bevorzugte Sprache',

    'share.title': 'Freigabezentrale',
    'share.description': 'Teilen Sie Passwörter sicher mit anderen Benutzern',
    'share.comingSoon': 'Diese Funktion wird bald verfügbar sein',

    'analysis.title': 'Passwortanalyse',
    'analysis.description': 'Analysieren Sie die Sicherheit Ihrer Passwörter',
    'analysis.comingSoon': 'Diese Funktion wird bald verfügbar sein',

    'common.loading': 'Lädt...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
  },
};

const languageNames: Record<Language, string> = {
  es: 'Español',
  en: 'English',
  pt: 'Português',
  fr: 'Français',
  de: 'Deutsch',
};

export const getLanguageName = (lang: Language) => languageNames[lang];
export const supportedLanguages: Language[] = ['es', 'en', 'pt', 'fr', 'de'];

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'es';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
